#!/bin/sh

. $SNAP/bin/default_config

config_dir=${SNAP_DATA}/etc/dovecot

test -d ${SNAP_DATA}/dovecot/log || mkdir -p ${SNAP_DATA}/dovecot/log
test -d ${SNAP_DATA}/dovecot/base || mkdir -p ${SNAP_DATA}/dovecot/base
test -d ${SNAP_DATA}/dovecot/state || mkdir -p ${SNAP_DATA}/dovecot/state

if [ ! -d ${config_dir} ]; then
   mkdir -p $config_dir

   cp -a ${SNAP}/conf/dovecot/* ${config_dir}
   for file in ${config_dir}/* ; 
   do 
       if [ -f ${file} ]; then
           modify "s#{SNAP}#${SNAP}#g" ${file}
           modify "s#{SNAP_DATA}#${SNAP_DATA}#g" ${file}
           modify "s#{DEFAULT_HOST_NAME}#${DEFAULT_HOST_NAME}#g" ${file}
       fi
   done
fi
