#!/bin/sh

. $SNAP/bin/default_config

config_directory=${SNAP_DATA}/conf/roundcube
test -d $config_directory || mkdir -p $config_directory
test -f $config_directory/config.inc.php || cp ${SNAP}/conf/roundcube/config.inc.php $config_directory
test -f $config_directory/defaults.inc.php || cp ${SNAP}/conf/roundcube/defaults.inc.php $config_directory

#waiting roundcube mysql password is generated. 
while [ ! -f "$SNAP_DATA/mysql/roundcube_password" ]; do
    sleep 1 
    echo "waiting for roundcube_password"
done 

roundcube_password=`cat $SNAP_DATA/mysql/roundcube_password`
modify "s#sql_passwd#${roundcube_password}#g" $config_directory/config.inc.php
modify "s#sql_passwd#${roundcube_password}#g" $config_directory/defaults.inc.php
