name: mail-all-in-one
version: 0.9.5-7
summary: A mail solution consists of a webmail client and a mail server.
description: |
  A mail solution takes lots of inspiration from nextcloud snap and iRedMail open source project. It puts all open source components that make up a whole mail solution into one snap.
  To view full default settings for this mail solution, please run
  $ mail-all-in-one.help

grade: devel
confinement: devmode

apps:
  #Postfix daemon
  postfix:
    command: run-postfix
    daemon: simple
    plugs: [network, network-bind, process-control]
  #Dovecot daemon
  dovecot:
    command: run-dovecot start
    daemon: forking
    plugs: [network, network-bind, process-control]
  #Apache daemon
  apache:
    command: run-httpd -k start -DFOREGROUND
    stop-command: run-httpd -k stop
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]
  #MySQL daemon
  mysql:
    command: start_mysql
    stop-command: support-files/mysql.server stop
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]
  # MySQL client
  mysql-client:
    command: mysql --defaults-file=$SNAP_DATA/mysql/vmailadmin.ini
    plugs: [network, network-bind]
  # PHP FPM daemon
  php-fpm:
    command: start-php-fpm
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]
  help:
    command: help

parts:
  postfix:
    plugin: make
    source: https://github.com/adglkh/postfix-snap-feature.git
    source-type: git
    source-subdir: postfix
    build-packages:
      - gcc
      - libdb5.3-dev 
      - libsasl2-dev
      - libicu-dev
      - libsqlite3-dev
      - libssl-dev
      - libpcre3-dev
    make-parameters:
      - CCARGS=-DENABLE_SNAP=1 -DHAS_MYSQL -I$SNAPCRAFT_STAGE/include -DUSE_CYRUS_SASL -DUSE_SASL_AUTH -I/usr/include/sasl -DDEF_SERVER_SASL_TYPE=\"dovecot\" 
      - AUXLIBS=-L$SNAPCRAFT_STAGE/lib/ -lmysqlclient -lsasl2 -lz -lm
    after:
      - mysql
  postfix-customizations:
    plugin: dump
    after:
      - postfix
    organize:
      "src/postfix/scripts/*": bin/
      "src/postfix/conf/*": conf/postfix/

  dovecot:
    plugin: autotools
    source: https://github.com/jindallo/dovecot-snap.git
    source-type: git
    after:
      - mysql
    build-packages:
      - libbz2-dev
      - libexttextcat-dev
      - liblz4-dev
      - liblzma-dev
      - libwrap0-dev
      - libssl-dev
    configflags:
      - --without-shared-libs
      - --with-ssl=openssl
      - --with-ssldir=/usr/include/openssl
      - --with-mysql
      - --enable-snap
    stage-packages:
      - openssl
    filesets:
      exclude:
        - -doc/
      stage:
        - $exclude
      prime:
        - $exclude
  dovecot-customizations:
    plugin: dump
    after:
      - dovecot
    organize:
      "src/dovecot/scripts/*": bin/
      "src/dovecot/conf/*": conf/dovecot/

  roundcube:
    plugin: dump
    source: https://github.com/roundcube/roundcubemail/releases/download/1.2.3/roundcubemail-1.2.3-complete.tar.gz
    organize:
      'index.php': htdocs/
      'plugins': htdocs/plugins/
      'program' : htdocs/program/
      'public_html' : htdocs/public_html/
      'skins' : htdocs/skins/
      'vendor' : htdocs/vendor/
      '.htaccess': htdocs/
      'robots.txt': htdocs/
    filesets:
      exclude:
        - -INSTALL
        - -CHANGELOG
        - -composer.json-dist
        - -temp
        - -logs
        - -config
        - -installer
        - -README.md
        - -SQL
        - -htdocs/program/include/iniset.php
    stage:
      - $exclude
    prime:
      - $exclude
  roundcube-customizations:
    plugin: dump
    after: 
      - roundcube
    organize:
      "src/roundcube/conf/*": conf/roundcube/
      "src/roundcube/ini/*": htdocs/program/include/
      "src/roundcube/scripts/*": bin/

  tools-customizations:
    plugin: dump
    organize:
      "src/tools/help": bin/
      "src/tools/default_config": bin/
      "src/tools/generate_ssha_password.py": bin/
      "src/tools/configure": meta/hooks/configure

  #It's required by iredadmin panel web frontend.
  mod-wsgi:
    plugin: autotools
    source: https://github.com/adglkh/mod_wsgi.git
    source-type: git
    source-branch: snap-feature
    configflags:
      - --enable-snap
      - --with-python=/usr/bin/python2
    build-packages:
      - python2.7
    after: 
      - apache

  python-env:
    plugin: python
    python-version: python2
    python-packages:
      - web.py
      - jinja2
      - mysql-python
    stage-packages:
      - python-all
    after: 
      - mysql

  iredadmin:
    plugin: dump
    source: https://github.com/adglkh/iRedAdmin-snap-feature.git
    source-type: git
    organize:
      '*': iredadmin/
    filesets:
      exclude:
        - -AUTHORS    
        - -README                   
        - -SQL     
        - -ChangeLog  
        - -docs         
        - -LICENSE  
        - -settings.py.mysql.sample  
        - -settings.py.ldap.sample  
        - -settings.py.pgsql.sample
    stage:
      - $exclude
    prime:
      - $exclude
  iredadmin-customizations:
    plugin: dump
    after:
      - iredadmin
    organize:
      "src/iredadmin/conf/*": conf/iredadmin/
      "src/iredadmin/ini/*": iredadmin/

  apache:
    plugin: apache
    source: http://ftp.wayne.edu/apache/httpd/httpd-2.4.25.tar.bz2

    # The built-in Apache modules to enable
    modules:
      - headers
      - proxy
      - proxy_fcgi
      - setenvif
      - env
      - rewrite
      - mime
      - dir
      - authz_core
      - unixd
      - alias
      - ssl
      - socache_shmcb

    filesets:
      exclude:
        - -man
        - -manual
        - -htdocs
        - -include
        - -build
        - -conf/httpd.conf
        - -conf/magic
        - -conf/original
        - -conf/extra
        - -bin/apachectl
        - -bin/envvars*
    stage:
      - $exclude
    prime:
      - $exclude

  apache-customizations:
    plugin: dump
    organize:
      "src/apache/scripts/*": bin/
      "src/apache/conf/*": conf/

  boost:
    #plugin: copy
    plugin: dump
    source: http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz
    #file:
    organize:
      '*': boost_1_59_0/
    prime:
      - -*

  mysql:
    plugin: cmake
    source: https://github.com/kyrofa/mysql-server.git
    source-type: git
    source-branch: feature/support_no_setpriority
    after: 
      - boost
    configflags:
      - -DWITH_BOOST=$SNAPCRAFT_STAGE/boost_1_59_0
      - -DWITH_INNODB_PAGE_CLEANER_PRIORITY=OFF
      - -DCMAKE_INSTALL_PREFIX=/
      - -DBUILD_CONFIG=mysql_release
      - -DWITH_UNIT_TESTS=OFF
      - -DWITH_EMBEDDED_SERVER=OFF
      - -DWITH_EMBEDDED_SHARED_LIBRARY=OFF
      - -DWITH_ARCHIVE_STORAGE_ENGINE=OFF
      - -DWITH_BLACKHOLE_STORAGE_ENGINE=OFF
      - -DWITH_FEDERATED_STORAGE_ENGINE=OFF
      - -DWITH_PARTITION_STORAGE_ENGINE=OFF
      - -DINSTALL_MYSQLTESTDIR=
    build-packages:
      - wget
      - g++
      - cmake
      - bison
      - libncurses5-dev
      - libaio-dev
    stage:
      # Remove scripts that we'll be replacing with our own
      - -support-files/mysql.server
    prime:
      # Remove scripts that we'll be replacing with our own
      - -support-files/mysql.server

      # Remove unused binaries that waste space
      - -bin/innochecksum
      - -bin/lz4_decompress
      - -bin/myisam*
      - -bin/mysqladmin
      - -bin/mysqlbinlog
      - -bin/mysql_client_test
      - -bin/mysql_config*
      - -bin/mysqld_multi
      - -bin/mysqldump*
      - -bin/mysqlimport
      - -bin/mysql_install_db
      - -bin/mysql_plugin
      - -bin/mysqlpump
      - -bin/mysql_secure_installation
      - -bin/mysqlshow
      - -bin/mysqlslap
      - -bin/mysql_ssl_rsa_setup
      - -bin/mysqltest
      - -bin/mysql_tzinfo_to_sql
      - -bin/perror
      - -bin/replace
      - -bin/resolveip
      - -bin/resolve_stack_dump
      - -bin/zlib_decompress
  # Copy over our MySQL scripts
  mysql-customizations:
    plugin: dump
    organize:
      # This one is what creates the initial database and account for postfix and roundcube.
      "src/mysql/start_mysql": bin/
      "src/mysql/my.cnf": my.cnf
      "src/mysql/mysql.server": support-files/
      "src/mysql/conf/*": conf/mysql/

  php:
    plugin: php 
    source: http://us1.php.net/get/php-7.0.15.tar.bz2/from/this/mirror
    source-type: tar 
    install-via: prefix
    configflags:
      - --enable-fpm
      - --disable-cgi
      - --disable-phar
      - --disable-phpdbg
      - --enable-ctype
      - --enable-mbstring
      - --enable-zip
      - --with-pdo-mysql
      - --with-zlib
      - --with-gd
      - --with-curl
      - --with-openssl
      - --with-bz2
      - --with-mcrypt
      - --enable-exif
      - --enable-intl
      - --with-jpeg-dir=/usr/lib
      - --disable-rpath
    stage-packages:
      # These are only included here until the OS snap stabilizes
      - libxml2
      - libpng12-0
    build-packages:
      - libxml2-dev
      - libcurl4-openssl-dev
      - libpng12-dev
      - libjpeg9-dev
      - libbz2-dev
      - libmcrypt-dev
    prime:
     - -sbin/
     - -etc/
    organize:
      # Put php-fpm in bin with everything else, not sbin.
      sbin/php-fpm: bin/php-fpm

  ## Copy over our PHP configuration file.
  php-customizations:
    plugin: dump
    organize:
      "src/php/config/*": conf/php/
      "src/php/scripts/*": bin/
    stage-packages: [mawk]
